name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'abrsm-base/**'
      - 'abrsm-base-light/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: abrsm-base
            image_name: abrsm-base
          - name: abrsm-base-light
            image_name: abrsm-base-light

    steps:
      - name: Check-out the repository code
        uses: actions/checkout@v3

      # === DEBUGGING STEP START ===
      # This step checks if the secrets are accessible in this workflow run.
      - name: Debug Secrets Availability
        run: |
          echo "Username is: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Token is available: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
      # === DEBUGGING STEP END ===

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service.image_name }}:latest
